// <auto-generated />
using System;
using Calcifer.Services.EventAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calcifer.Services.EventAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Calcifer.Services.EventAPI.Models.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceVenue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId");

                    b.ToTable("Event", (string)null);

                    b.HasData(
                        new
                        {
                            EventId = new Guid("72caf757-103b-42b2-8731-d938f7dca3f7"),
                            Category = "drinks",
                            City = "Stockholm",
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Great Party",
                            PlaceVenue = "Pub",
                            Title = "Past Activity 1"
                        },
                        new
                        {
                            EventId = new Guid("ce03d3c4-b2fc-4b7f-b042-1c93f93fb58d"),
                            Category = "culture",
                            City = "Sundbyberg",
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "lol",
                            PlaceVenue = "Willys",
                            Title = "Future Activity 1"
                        },
                        new
                        {
                            EventId = new Guid("a125ca18-ee7e-468f-932a-e60fa408008e"),
                            Category = "music",
                            City = "Varnamo",
                            Date = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Kom",
                            PlaceVenue = "Lagan",
                            Title = "Future Activity 2"
                        },
                        new
                        {
                            EventId = new Guid("39485834-bb59-4f2a-9bc3-b3d81c90cce1"),
                            Category = "travel",
                            City = "Orebro",
                            Date = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Fest",
                            PlaceVenue = "Torget",
                            Title = "Future Activity 3"
                        },
                        new
                        {
                            EventId = new Guid("b9b291a6-b5c7-4de0-a611-3d719db50df1"),
                            Category = "film",
                            City = "Uppsala",
                            Date = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Bio",
                            PlaceVenue = "Stora Torget",
                            Title = "Future Activity 4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
